---

- name: show certificate name
  ansible.builtin.debug:
    msg: 'deploy {{ cert_item.name }}'
  when: ansible_check_mode or ansible_diff_mode

# -----------------------------------------------------------------------------
# key
# -----------------------------------------------------------------------------

- name: create key directory
  ansible.builtin.file:
    path: '{{ cert_item.key.dest | dirname }}'
    state: directory
    owner: root
    group: root
    mode: '{{ cert_item.key.mode | default("0755") }}'
    setype: '{{ cert_item.key.setype | default("cert_t") }}'

- name: install key
  ansible.builtin.copy:
    content: '{{ cert_item.key.content }}'
    dest: '{{ cert_item.key.dest }}'
    owner: root
    group: root
    mode: '{{ cert_item.key.acl_users is defined | ternary("0640", "0600") }}'
    setype: '{{ cert_item.key.setype | default("cert_t") }}'

- name: set key acl entries
  ansible.posix.acl:
    path: '{{ cert_item.key.dest }}'
    entity: '{{ user_item }}'
    etype: user
    permissions: r
    state: present
  when: cert_item.key.acl_users is defined
  loop: '{{ cert_item.key.acl_users }}'
  loop_control:
    loop_var: user_item

# -----------------------------------------------------------------------------
# certificate
# -----------------------------------------------------------------------------

- name: create certificate directory
  ansible.builtin.file:
    path: '{{ cert_item.cert.dest | dirname }}'
    state: directory
    owner: root
    group: root
    mode: 0755
    setype: '{{ cert_item.key.setype | default("cert_t") }}'

- name: install certificate
  ansible.builtin.copy:
    src: '{{ cert_item.cert.src }}'
    dest: '{{ cert_item.cert.dest }}'
    owner: root
    group: root
    mode: 0644
    setype: '{{ cert_item.key.setype | default("cert_t") }}'

# -----------------------------------------------------------------------------
# chain (optional)
# -----------------------------------------------------------------------------

- name: create chain directory
  ansible.builtin.file:
    path: '{{ cert_item.chain.dest | dirname }}'
    state: directory
    owner: root
    group: root
    mode: 0755
    setype: '{{ cert_item.key.setype | default("cert_t") }}'
  when: cert_item.chain is defined

- name: install chain
  ansible.builtin.copy:
    src: '{{ cert_item.chain.src }}'
    dest: '{{ cert_item.chain.dest }}'
    owner: root
    group: root
    mode: 0644
    setype: '{{ cert_item.key.setype | default("cert_t") }}'
  when: cert_item.chain is defined

...
